title: "YAO Research Group"
short-title: "YAO"
description: "Default subtitle"
author: "Aeksio"

baseurl: ""
url: "https://yaokgroup.github.io"

site-css:
  - "/assets/css/custom-styles.css"

navbar-links:
  Home: ""
  Research: "research"
  Members: "members"
  Publications: "publications"
  Gallery: "gallery"
  Contact: "contact"

# footer links
social-network-links:
  google-scholar: "https://scholar.google.com/citations?user=dthwMXwAAAAJ&hl=en&oi=ao"
  linkedin: "https://www.linkedin.com/in/kuanming-yao-26a1b8267/"
  orcid: "https://orcid.org/0000-0001-8744-8892"
  researchgate: "https://www.researchgate.net/profile/Kuanming-Yao"
